### ISSUE TITLE
Theme is 6.81Mb to clone ...

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook-theme#2]
Theme is quite large to clone even though actual master looks to be under a MB ...

Is there a reason?

**Comment by smth** [comment]
That sounds the wrong way around. On my machine, this theme is 720KB, while the Open Data Handbook (is that what you mean by "master"?) is 5.9MB.

**Comment by rufuspollock** [comment]
What i mean is `du -sh` on master after checkout is under a MB but `du -sh` on .git yields around 7MB ...

**Comment by smth** [comment]
I'm not entirely sure what those commands do. Is it including git history? i.e adding the size of the Open Data Handbook, because that is what this repo is derived from.

**Comment by rufuspollock** [comment]
Yes, those include the history. The answer is that we included the entire history. We may want to rewrite that at some point so we have a fairly clean history but probably not now ;-)
